fruits=('apple','orange','grape')
print(fruits)
print(type(fruits))
print(len(fruits))
print(fruits[1])
print(fruits[-1])
fruits1=list(fruits)
print(fruits1)
fruits1[1]="kiwi"
print(fruits1)
fruits=tuple(fruits1)
print(fruits)
fruits2=list(fruits)
print(fruits2)
fruits2.remove('grape')
print(fruits2)
fruits=tuple(fruits2)
print(fruits)
vegitable=(1,2,3,4,5,3,3,2)
x=vegitable.count(3)# to fint the count of iteams
print(x)
y=vegitable.index(3)#to find the fist number that we find
print(y)
num1=(1,2,4,5,7,8,10,2,4,5,3)
print(num1)
num2=list(num1)
print(num2)
num2.append(9)
print(num2)
num2.sort()
print(num2)
print(len(num2))
num2[1]=12
print(num2)
num1=tuple(num2)
print(num1)
a=num2.count(4)
print(a)
b=num2.index(4)
print(b)
for i in fruits:
    print(i)
for i in range(len(fruits)):
    print(fruits[i])